import { Injectable } from '@angular/core';
import { of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class TicketService {
  constructor() {}

  getTickets() {
    return of([
      {
        date: '2024-07-27',
        time: '09:09:52',
        ticket:'23',
        username: 'Adam',
        branchCode: 'HHH',
        branchName: 'Central City',
        reasonforCall: 'Clocking Issue',
        clockNumber: '001',
        issue: 'Camera Not Working',
        reportedAt: 'Head office',
        resolved: 'N',
        newStore: 'Y',
        notes: 'Test Note',
        status: 'Resolved',
        reasonForChange: 'NA',
        transferTo: 'Admin',
        transferredFrom: 'IT',
        assignedTo: 'Adam',
        numberOfFiles: '2',
        files: '',
      },

      {
        date: '2024-01-17',
        time: '03:02:52',
        ticket:'24',
        username: 'James',
        branchCode: 'AD1',
        branchName: 'Cape Town',
        reasonforCall: 'Clocking Issue',
        clockNumber: '001',
        issue: 'Camera Not Working',
        reportedAt: 'Store',
        resolved: 'N',
        newStore: 'Y',
        notes: 'Test Note 2',
        status: 'Pending',
        reasonForChange: 'NA',
        transferTo: 'HR',
        transferredFrom: 'Admin',
        assignedTo: 'Smith',
        numberOfFiles: '3',
        files: '',
      },

      {
        date: '2023-11-11',
        time: '10:25:52',
        ticket:'25',
        username: 'Paul',
        branchCode: 'BC1',
        branchName: 'Durban',
        reasonforCall: 'Clocking Issue',
        clockNumber: '003',
        issue: 'Camera Not Working',
        reportedAt: 'Warehouse',
        resolved: 'Y',
        newStore: 'F',
        notes: 'Test Note 3',
        status: 'In Progress',
        reasonForChange: 'NA',
        transferTo: 'Sale',
        transferredFrom: 'IT',
        assignedTo: 'David',
        numberOfFiles: '3',
        files: '',
      },

      {
        date: '2024-04-29',
        time: '04:04:52',
        ticket:'26',
        username: 'Daniel',
        branchCode: 'GC1',
        branchName: 'Johansanburg',
        reasonforCall: 'Clocking Issue',
        clockNumber: '005',
        issue: 'Camera Not Working',
        reportedAt: 'Rage',
        resolved: 'N',
        newStore: 'Y',
        notes: 'Test Note 4',
        status: 'Resolved',
        reasonForChange: 'NA',
        transferTo: 'Buying',
        transferredFrom: 'Banking',
        assignedTo: 'Amy',
        numberOfFiles: '2',
        files: '',
      },

      {
        date: '2024-04-04',
        time: '09:09:52',
        ticket:'23',
        username: 'Sean',
        branchCode: 'AAR',
        branchName: 'TIANE RAGE',
        reasonforCall: 'Clocking Issue',
        clockNumber: '2333',
        issue: 'Camera Not Working',
        reportedAt: 'Head office',
        resolved: 'N',
        newStore: 'Y',
        notes: 'Test Note',
        status: 'Resolved',
        reasonForChange: 'NA',
        transferTo: 'Admin',
        transferredFrom: 'IT',
        assignedTo: 'Adam',
        numberOfFiles: '2',
        files: '',
      },
    
    ]);
  }
}
